input_data_path: "data/heart.csv"
categorical_features:
  - "sex"
  - "cp"
  - "fbs"
  - "restecg"
  - "exang"
  - "slope"
  - "ca"
  - "thal"
numerical_features:
  - "age"
  - "trestbps"
  - "chol"
  - "thalach"
  - "oldpeak"
target_col: "target"
