apiVersion: v1
kind: Pod
metadata:
  name: online-inference-hw4
  labels:
    app: online-inference-hw4
spec:
  containers:
    - image: n0tanbi4/online-inference-hw4:latest
      name: online-inference-hw4
      ports:
        - containerPort: 8000

      resources:
        requests:
          memory: 512Mi
          cpu: 700m

      readinessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 25
        periodSeconds: 10

      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 25
        periodSeconds: 10
